apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.component_id }}-dev
spec:
  destination:
    namespace: ${{ values.component_id }}-dev
    server: https://kubernetes.default.svc
  project: janus
  source:
    helm:
      valueFiles:
       - values.yaml
    path: helm
    repoURL: 'https://github.com/nmalvank-org/spring-petclinic97-gitops.git'
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
