apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: ${{ values.component_id }}
    app.kubernetes.io/component: web
    app.kubernetes.io/instance: ${{ values.component_id }}
    app.kubernetes.io/name: ${{ values.component_id }}
    app.kubernetes.io/part-of: ${{ values.component_id }}
    app.openshift.io/runtime: java
  name: ${{ values.component_id }}
spec:
  replicas: {{ .Values.petclinic.replicas }}
  selector:
    matchLabels:
      app: ${{ values.component_id }}
  template:
    metadata:
      labels:
        app: ${{ values.component_id }}
    spec:
      containers:
      - name: ${{ values.component_id }}
        imagePullPolicy: Always
        image: {{ .Values.petclinic.image }}:{{ .Values.petclinic.tag }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8778
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5          
